export const COUNTRIES_EN = {
  'Costa Rica': 'CR',
  Nicaragua: 'NI',
  Haiti: 'HT',
  'Dominican Republic': 'DO',
  'El Salvador': 'SV',
  Guatemala: 'GT',
  Cuba: 'CU',
  Honduras: 'HN',
  'United States of America': 'US',
  Canada: 'CA',
  Mexico: 'MX',
  Belize: 'BZ',
  Panama: 'PA',
  Greenland: 'GL',
  'The Bahamas': 'BS',
  'Trinidad and Tobago': 'TT',
  'Puerto Rico': 'PR',
  Jamaica: 'JM',
  Indonesia: 'ID',
  Malaysia: 'MY',
  Cyprus: 'CY',
  India: 'IN',
  "People's Republic of China": 'CN',
  Israel: 'IL',
  Palestine: 'PS',
  Lebanon: 'LB',
  Syria: 'SY',
  'South Korea': 'KR',
  'North Korea': 'KP',
  Bhutan: 'BT',
  Oman: 'OM',
  Uzbekistan: 'UZ',
  Kazakhstan: 'KZ',
  Tajikistan: 'TJ',
  Mongolia: 'MN',
  Vietnam: 'VN',
  Cambodia: 'KH',
  'United Arab Emirates': 'AE',
  Georgia: 'GE',
  Azerbaijan: 'AZ',
  Turkey: 'TR',
  Laos: 'LA',
  Kyrgyzstan: 'KG',
  Armenia: 'AM',
  Iraq: 'IQ',
  Iran: 'IR',
  Qatar: 'QA',
  'Saudi Arabia': 'SA',
  Pakistan: 'PK',
  Thailand: 'TH',
  Kuwait: 'KW',
  'East Timor': 'TL',
  Brunei: 'BN',
  Myanmar: 'MM',
  Bangladesh: 'BD',
  Afghanistan: 'AF',
  Turkmenistan: 'TM',
  Jordan: 'JO',
  Nepal: 'NP',
  Yemen: 'YE',
  'Turkish Republic of Northern Cyprus': '-99',
  Philippines: 'PH',
  'Sri Lanka': 'LK',
  Taiwan: 'CN-TW',
  Japan: 'JP',
  Chile: 'CL',
  Bolivia: 'BO',
  Peru: 'PE',
  Argentina: 'AR',
  Suriname: 'SR',
  Guyana: 'GY',
  Brazil: 'BR',
  Uruguay: 'UY',
  Ecuador: 'EC',
  Colombia: 'CO',
  Paraguay: 'PY',
  Venezuela: 'VE',
  'Falkland Islands': 'FK',
  Ethiopia: 'ET',
  'South Sudan': 'SS',
  Somalia: 'SO',
  Kenya: 'KE',
  Malawi: 'MW',
  Tanzania: 'TZ',
  Somaliland: '-99',
  Morocco: 'MA',
  'Western Sahara': 'EH',
  'Republic of the Congo': 'CG',
  'Democratic Republic of the Congo': 'CD',
  Namibia: 'NA',
  'South Africa': 'ZA',
  Libya: 'LY',
  Tunisia: 'TN',
  Zambia: 'ZM',
  'Sierra Leone': 'SL',
  Guinea: 'GN',
  Liberia: 'LR',
  'Central African Republic': 'CF',
  Sudan: 'SD',
  Djibouti: 'DJ',
  Eritrea: 'ER',
  'Ivory Coast': 'CI',
  Mali: 'ML',
  Senegal: 'SN',
  Nigeria: 'NG',
  Benin: 'BJ',
  Angola: 'AO',
  Botswana: 'BW',
  Zimbabwe: 'ZW',
  Chad: 'TD',
  Algeria: 'DZ',
  Mozambique: 'MZ',
  Eswatini: 'SZ',
  Burundi: 'BI',
  Rwanda: 'RW',
  Uganda: 'UG',
  Lesotho: 'LS',
  Cameroon: 'CM',
  Gabon: 'GA',
  Niger: 'NE',
  'Burkina Faso': 'BF',
  Togo: 'TG',
  Ghana: 'GH',
  'Guinea-Bissau': 'GW',
  Egypt: 'EG',
  Mauritania: 'MR',
  'Equatorial Guinea': 'GQ',
  'The Gambia': 'GM',
  Madagascar: 'MG',
  France: '-99',
  Ukraine: 'UA',
  Belarus: 'BY',
  Lithuania: 'LT',
  Russia: 'RU',
  'Czech Republic': 'CZ',
  Germany: 'DE',
  Estonia: 'EE',
  Latvia: 'LV',
  Norway: '-99',
  Sweden: 'SE',
  Finland: 'FI',
  Luxembourg: 'LU',
  Belgium: 'BE',
  'North Macedonia': 'MK',
  Albania: 'AL',
  Kosovo: '-99',
  Spain: 'ES',
  Denmark: 'DK',
  Romania: 'RO',
  Hungary: 'HU',
  Slovakia: 'SK',
  Poland: 'PL',
  Ireland: 'IE',
  'United Kingdom': 'GB',
  Greece: 'GR',
  Austria: 'AT',
  Italy: 'IT',
  Switzerland: 'CH',
  Netherlands: 'NL',
  Serbia: 'RS',
  Croatia: 'HR',
  Slovenia: 'SI',
  Bulgaria: 'BG',
  Montenegro: 'ME',
  'Bosnia and Herzegovina': 'BA',
  Portugal: 'PT',
  Moldova: 'MD',
  Iceland: 'IS',
  'Papua New Guinea': 'PG',
  Australia: 'AU',
  Fiji: 'FJ',
  'New Zealand': 'NZ',
  'New Caledonia': 'NC',
  'Solomon Islands': 'SB',
  Vanuatu: 'VU',
  Antarctica: 'AQ',
  'French Southern and Antarctic Lands': 'TF',
};
