export const COUNTRIES_ES = {
  'Costa Rica': 'CR',
  Nicaragua: 'NI',
  Haití: 'HT',
  'República Dominicana': 'DO',
  'El Salvador': 'SV',
  Guatemala: 'GT',
  Cuba: 'CU',
  Honduras: 'HN',
  'Estados Unidos': 'US',
  Canadá: 'CA',
  México: 'MX',
  Belice: 'BZ',
  Panamá: 'PA',
  Groenlandia: 'GL',
  Bahamas: 'BS',
  'Trinidad y Tobago': 'TT',
  'Puerto Rico': 'PR',
  Jamaica: 'JM',
  Indonesia: 'ID',
  Malasia: 'MY',
  Chipre: 'CY',
  India: 'IN',
  China: 'CN',
  Israel: 'IL',
  Palestina: 'PS',
  Líbano: 'LB',
  Siria: 'SY',
  'Corea del Sur': 'KR',
  'Corea del Norte': 'KP',
  Bután: 'BT',
  Omán: 'OM',
  Uzbekistán: 'UZ',
  Kazajistán: 'KZ',
  Tayikistán: 'TJ',
  Mongolia: 'MN',
  Vietnam: 'VN',
  Camboya: 'KH',
  'Emiratos Árabes Unidos': 'AE',
  Georgia: 'GE',
  Azerbaiyán: 'AZ',
  Turquía: 'TR',
  Laos: 'LA',
  Kirguistán: 'KG',
  Armenia: 'AM',
  Irak: 'IQ',
  Irán: 'IR',
  Catar: 'QA',
  'Arabia Saudita': 'SA',
  Pakistán: 'PK',
  Tailandia: 'TH',
  Kuwait: 'KW',
  'Timor Oriental': 'TL',
  Brunéi: 'BN',
  Birmania: 'MM',
  Bangladés: 'BD',
  Afganistán: 'AF',
  Turkmenistán: 'TM',
  Jordania: 'JO',
  Nepal: 'NP',
  Yemen: 'YE',
  'República Turca del Norte de Chipre': '-99',
  Filipinas: 'PH',
  'Sri Lanka': 'LK',
  'República de China': 'CN-TW',
  Japón: 'JP',
  Chile: 'CL',
  Bolivia: 'BO',
  Perú: 'PE',
  Argentina: 'AR',
  Surinam: 'SR',
  Guyana: 'GY',
  Brasil: 'BR',
  Uruguay: 'UY',
  Ecuador: 'EC',
  Colombia: 'CO',
  Paraguay: 'PY',
  Venezuela: 'VE',
  'Islas Malvinas': 'FK',
  Etiopía: 'ET',
  'Sudán del Sur': 'SS',
  Somalia: 'SO',
  Kenia: 'KE',
  Malaui: 'MW',
  Tanzania: 'TZ',
  Somalilandia: '-99',
  Marruecos: 'MA',
  'Sahara Occidental': 'EH',
  'República del Congo': 'CG',
  'República Democrática del Congo': 'CD',
  Namibia: 'NA',
  Sudáfrica: 'ZA',
  Libia: 'LY',
  Túnez: 'TN',
  Zambia: 'ZM',
  'Sierra Leona': 'SL',
  Guinea: 'GN',
  Liberia: 'LR',
  'República Centroafricana': 'CF',
  Sudán: 'SD',
  Yibuti: 'DJ',
  Eritrea: 'ER',
  'Costa de Marfil': 'CI',
  Malí: 'ML',
  Senegal: 'SN',
  Nigeria: 'NG',
  Benín: 'BJ',
  Angola: 'AO',
  Botsuana: 'BW',
  Zimbabue: 'ZW',
  Chad: 'TD',
  Argelia: 'DZ',
  Mozambique: 'MZ',
  Suazilandia: 'SZ',
  Burundi: 'BI',
  Ruanda: 'RW',
  Uganda: 'UG',
  Lesoto: 'LS',
  Camerún: 'CM',
  Gabón: 'GA',
  Níger: 'NE',
  'Burkina Faso': 'BF',
  Togo: 'TG',
  Ghana: 'GH',
  'Guinea-Bisáu': 'GW',
  Egipto: 'EG',
  Mauritania: 'MR',
  'Guinea Ecuatorial': 'GQ',
  Gambia: 'GM',
  Madagascar: 'MG',
  Francia: '-99',
  Ucrania: 'UA',
  Bielorrusia: 'BY',
  Lituania: 'LT',
  Rusia: 'RU',
  'República Checa': 'CZ',
  Alemania: 'DE',
  Estonia: 'EE',
  Letonia: 'LV',
  Noruega: '-99',
  Suecia: 'SE',
  Finlandia: 'FI',
  Luxemburgo: 'LU',
  Bélgica: 'BE',
  'Macedonia del Norte': 'MK',
  Albania: 'AL',
  Kosovo: '-99',
  España: 'ES',
  Dinamarca: 'DK',
  Rumania: 'RO',
  Hungría: 'HU',
  Eslovaquia: 'SK',
  Polonia: 'PL',
  Irlanda: 'IE',
  'Reino Unido': 'GB',
  Grecia: 'GR',
  Austria: 'AT',
  Italia: 'IT',
  Suiza: 'CH',
  'Países Bajos': 'NL',
  Serbia: 'RS',
  Croacia: 'HR',
  Eslovenia: 'SI',
  Bulgaria: 'BG',
  Montenegro: 'ME',
  'Bosnia y Herzegovina': 'BA',
  Portugal: 'PT',
  Moldavia: 'MD',
  Islandia: 'IS',
  'Papúa Nueva Guinea': 'PG',
  Australia: 'AU',
  Fiyi: 'FJ',
  'Nueva Zelanda': 'NZ',
  'Nueva Caledonia': 'NC',
  'Islas Salomón': 'SB',
  Vanuatu: 'VU',
  Antártida: 'AQ',
  'Tierras Australes y Antárticas Francesas': 'TF',
};
