export const COUNTRIES_ES = {
  'Costa Rica': 'CRI',
  Nicaragua: 'NIC',
  Haití: 'HTI',
  'República Dominicana': 'DOM',
  'El Salvador': 'SLV',
  Guatemala: 'GTM',
  Cuba: 'CUB',
  Honduras: 'HND',
  'Estados Unidos': 'USA',
  Canadá: 'CAN',
  México: 'MEX',
  Belice: 'BLZ',
  Panamá: 'PAN',
  Groenlandia: 'GRL',
  Bahamas: 'BHS',
  'Trinidad y Tobago': 'TTO',
  'Puerto Rico': 'PRI',
  Jamaica: 'JAM',
  Indonesia: 'IDN',
  Malasia: 'MYS',
  Chipre: 'CYP',
  India: 'IND',
  China: 'CHN',
  Israel: 'ISR',
  Palestina: 'PSE',
  Líbano: 'LBN',
  Siria: 'SYR',
  'Corea del Sur': 'KOR',
  'Corea del Norte': 'PRK',
  Bután: 'BTN',
  Omán: 'OMN',
  Uzbekistán: 'UZB',
  Kazajistán: 'KAZ',
  Tayikistán: 'TJK',
  Mongolia: 'MNG',
  Vietnam: 'VNM',
  Camboya: 'KHM',
  'Emiratos Árabes Unidos': 'ARE',
  Georgia: 'GEO',
  Azerbaiyán: 'AZE',
  Turquía: 'TUR',
  Laos: 'LAO',
  Kirguistán: 'KGZ',
  Armenia: 'ARM',
  Irak: 'IRQ',
  Irán: 'IRN',
  Catar: 'QAT',
  'Arabia Saudita': 'SAU',
  Pakistán: 'PAK',
  Tailandia: 'THA',
  Kuwait: 'KWT',
  'Timor Oriental': 'TLS',
  Brunéi: 'BRN',
  Birmania: 'MMR',
  Bangladés: 'BGD',
  Afganistán: 'AFG',
  Turkmenistán: 'TKM',
  Jordania: 'JOR',
  Nepal: 'NPL',
  Yemen: 'YEM',
  'República Turca del Norte de Chipre': '-99',
  Filipinas: 'PHL',
  'Sri Lanka': 'LKA',
  'República de China': 'TWN',
  Japón: 'JPN',
  Chile: 'CHL',
  Bolivia: 'BOL',
  Perú: 'PER',
  Argentina: 'ARG',
  Surinam: 'SUR',
  Guyana: 'GUY',
  Brasil: 'BRA',
  Uruguay: 'URY',
  Ecuador: 'ECU',
  Colombia: 'COL',
  Paraguay: 'PRY',
  Venezuela: 'VEN',
  'Islas Malvinas': 'FLK',
  Etiopía: 'ETH',
  'Sudán del Sur': 'SSD',
  Somalia: 'SOM',
  Kenia: 'KEN',
  Malaui: 'MWI',
  Tanzania: 'TZA',
  Somalilandia: '-99',
  Marruecos: 'MAR',
  'Sahara Occidental': 'ESH',
  'República del Congo': 'COG',
  'República Democrática del Congo': 'COD',
  Namibia: 'NAM',
  Sudáfrica: 'ZAF',
  Libia: 'LBY',
  Túnez: 'TUN',
  Zambia: 'ZMB',
  'Sierra Leona': 'SLE',
  Guinea: 'GIN',
  Liberia: 'LBR',
  'República Centroafricana': 'CAF',
  Sudán: 'SDN',
  Yibuti: 'DJI',
  Eritrea: 'ERI',
  'Costa de Marfil': 'CIV',
  Malí: 'MLI',
  Senegal: 'SEN',
  Nigeria: 'NGA',
  Benín: 'BEN',
  Angola: 'AGO',
  Botsuana: 'BWA',
  Zimbabue: 'ZWE',
  Chad: 'TCD',
  Argelia: 'DZA',
  Mozambique: 'MOZ',
  Suazilandia: 'SWZ',
  Burundi: 'BDI',
  Ruanda: 'RWA',
  Uganda: 'UGA',
  Lesoto: 'LSO',
  Camerún: 'CMR',
  Gabón: 'GAB',
  Níger: 'NER',
  'Burkina Faso': 'BFA',
  Togo: 'TGO',
  Ghana: 'GHA',
  'Guinea-Bisáu': 'GNB',
  Egipto: 'EGY',
  Mauritania: 'MRT',
  'Guinea Ecuatorial': 'GNQ',
  Gambia: 'GMB',
  Madagascar: 'MDG',
  Francia: '-99',
  Ucrania: 'UKR',
  Bielorrusia: 'BLR',
  Lituania: 'LTU',
  Rusia: 'RUS',
  'República Checa': 'CZE',
  Alemania: 'DEU',
  Estonia: 'EST',
  Letonia: 'LVA',
  Noruega: '-99',
  Suecia: 'SWE',
  Finlandia: 'FIN',
  Luxemburgo: 'LUX',
  Bélgica: 'BEL',
  'Macedonia del Norte': 'MKD',
  Albania: 'ALB',
  Kosovo: '-99',
  España: 'ESP',
  Dinamarca: 'DNK',
  Rumania: 'ROU',
  Hungría: 'HUN',
  Eslovaquia: 'SVK',
  Polonia: 'POL',
  Irlanda: 'IRL',
  'Reino Unido': 'GBR',
  Grecia: 'GRC',
  Austria: 'AUT',
  Italia: 'ITA',
  Suiza: 'CHE',
  'Países Bajos': 'NLD',
  Serbia: 'SRB',
  Croacia: 'HRV',
  Eslovenia: 'SVN',
  Bulgaria: 'BGR',
  Montenegro: 'MNE',
  'Bosnia y Herzegovina': 'BIH',
  Portugal: 'PRT',
  Moldavia: 'MDA',
  Islandia: 'ISL',
  'Papúa Nueva Guinea': 'PNG',
  Australia: 'AUS',
  Fiyi: 'FJI',
  'Nueva Zelanda': 'NZL',
  'Nueva Caledonia': 'NCL',
  'Islas Salomón': 'SLB',
  Vanuatu: 'VUT',
  Antártida: 'ATA',
  'Tierras Australes y Antárticas Francesas': 'ATF',
};
