export const COUNTRIES_EN = {
  'Costa Rica': 'CRI',
  Nicaragua: 'NIC',
  Haiti: 'HTI',
  'Dominican Republic': 'DOM',
  'El Salvador': 'SLV',
  Guatemala: 'GTM',
  Cuba: 'CUB',
  Honduras: 'HND',
  'United States of America': 'USA',
  Canada: 'CAN',
  Mexico: 'MEX',
  Belize: 'BLZ',
  Panama: 'PAN',
  Greenland: 'GRL',
  'The Bahamas': 'BHS',
  'Trinidad and Tobago': 'TTO',
  'Puerto Rico': 'PRI',
  Jamaica: 'JAM',
  Indonesia: 'IDN',
  Malaysia: 'MYS',
  Cyprus: 'CYP',
  India: 'IND',
  "People's Republic of China": 'CHN',
  Israel: 'ISR',
  Palestine: 'PSE',
  Lebanon: 'LBN',
  Syria: 'SYR',
  'South Korea': 'KOR',
  'North Korea': 'PRK',
  Bhutan: 'BTN',
  Oman: 'OMN',
  Uzbekistan: 'UZB',
  Kazakhstan: 'KAZ',
  Tajikistan: 'TJK',
  Mongolia: 'MNG',
  Vietnam: 'VNM',
  Cambodia: 'KHM',
  'United Arab Emirates': 'ARE',
  Georgia: 'GEO',
  Azerbaijan: 'AZE',
  Turkey: 'TUR',
  Laos: 'LAO',
  Kyrgyzstan: 'KGZ',
  Armenia: 'ARM',
  Iraq: 'IRQ',
  Iran: 'IRN',
  Qatar: 'QAT',
  'Saudi Arabia': 'SAU',
  Pakistan: 'PAK',
  Thailand: 'THA',
  Kuwait: 'KWT',
  'East Timor': 'TLS',
  Brunei: 'BRN',
  Myanmar: 'MMR',
  Bangladesh: 'BGD',
  Afghanistan: 'AFG',
  Turkmenistan: 'TKM',
  Jordan: 'JOR',
  Nepal: 'NPL',
  Yemen: 'YEM',
  'Turkish Republic of Northern Cyprus': '-99',
  Philippines: 'PHL',
  'Sri Lanka': 'LKA',
  Taiwan: 'TWN',
  Japan: 'JPN',
  Chile: 'CHL',
  Bolivia: 'BOL',
  Peru: 'PER',
  Argentina: 'ARG',
  Suriname: 'SUR',
  Guyana: 'GUY',
  Brazil: 'BRA',
  Uruguay: 'URY',
  Ecuador: 'ECU',
  Colombia: 'COL',
  Paraguay: 'PRY',
  Venezuela: 'VEN',
  'Falkland Islands': 'FLK',
  Ethiopia: 'ETH',
  'South Sudan': 'SSD',
  Somalia: 'SOM',
  Kenya: 'KEN',
  Malawi: 'MWI',
  Tanzania: 'TZA',
  Somaliland: '-99',
  Morocco: 'MAR',
  'Western Sahara': 'ESH',
  'Republic of the Congo': 'COG',
  'Democratic Republic of the Congo': 'COD',
  Namibia: 'NAM',
  'South Africa': 'ZAF',
  Libya: 'LBY',
  Tunisia: 'TUN',
  Zambia: 'ZMB',
  'Sierra Leone': 'SLE',
  Guinea: 'GIN',
  Liberia: 'LBR',
  'Central African Republic': 'CAF',
  Sudan: 'SDN',
  Djibouti: 'DJI',
  Eritrea: 'ERI',
  'Ivory Coast': 'CIV',
  Mali: 'MLI',
  Senegal: 'SEN',
  Nigeria: 'NGA',
  Benin: 'BEN',
  Angola: 'AGO',
  Botswana: 'BWA',
  Zimbabwe: 'ZWE',
  Chad: 'TCD',
  Algeria: 'DZA',
  Mozambique: 'MOZ',
  Eswatini: 'SWZ',
  Burundi: 'BDI',
  Rwanda: 'RWA',
  Uganda: 'UGA',
  Lesotho: 'LSO',
  Cameroon: 'CMR',
  Gabon: 'GAB',
  Niger: 'NER',
  'Burkina Faso': 'BFA',
  Togo: 'TGO',
  Ghana: 'GHA',
  'Guinea-Bissau': 'GNB',
  Egypt: 'EGY',
  Mauritania: 'MRT',
  'Equatorial Guinea': 'GNQ',
  'The Gambia': 'GMB',
  Madagascar: 'MDG',
  France: '-99',
  Ukraine: 'UKR',
  Belarus: 'BLR',
  Lithuania: 'LTU',
  Russia: 'RUS',
  'Czech Republic': 'CZE',
  Germany: 'DEU',
  Estonia: 'EST',
  Latvia: 'LVA',
  Norway: '-99',
  Sweden: 'SWE',
  Finland: 'FIN',
  Luxembourg: 'LUX',
  Belgium: 'BEL',
  'North Macedonia': 'MKD',
  Albania: 'ALB',
  Kosovo: '-99',
  Spain: 'ESP',
  Denmark: 'DNK',
  Romania: 'ROU',
  Hungary: 'HUN',
  Slovakia: 'SVK',
  Poland: 'POL',
  Ireland: 'IRL',
  'United Kingdom': 'GBR',
  Greece: 'GRC',
  Austria: 'AUT',
  Italy: 'ITA',
  Switzerland: 'CHE',
  Netherlands: 'NLD',
  Serbia: 'SRB',
  Croatia: 'HRV',
  Slovenia: 'SVN',
  Bulgaria: 'BGR',
  Montenegro: 'MNE',
  'Bosnia and Herzegovina': 'BIH',
  Portugal: 'PRT',
  Moldova: 'MDA',
  Iceland: 'ISL',
  'Papua New Guinea': 'PNG',
  Australia: 'AUS',
  Fiji: 'FJI',
  'New Zealand': 'NZL',
  'New Caledonia': 'NCL',
  'Solomon Islands': 'SLB',
  Vanuatu: 'VUT',
  Antarctica: 'ATA',
  'French Southern and Antarctic Lands': 'ATF',
};
